functions: make debug message more specific
The message:

  ERROR: Input parameters not provided

is too general to distinguish from others. Add function name so that
user can have more info on that.

Signed-off-by: Feng Mu <Feng.Mu@windriver.com>